config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'main#index'

  get '/rounds/factory', to: 'rounds#factory'
  get '/my_courses', to: 'courses#index_created'
  get '/golfed_courses', to: 'courses#index_golfed'
  get '/my_rounds', to: 'rounds#index_user'
  get '/course_rounds', to: 'rounds#index_course'
  get '/stats', to: 'main#stats'

  resources :rounds, shallow: true do
    resources :scorecards
  end

  resources :courses, shallow: true do
    resources :tees, except: [:show]
    resources :holes
  end

  resources :courses do
    resources :tees, only: [:show]
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def stats
  end

  def index
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_averages.html.erb
<div class="row mt-2">
  <div class="col">
    <ul class="list-group text-center mt-2">
      <li class="list-group-item list-group-item-secondary p-2">
        <h6 class="p-0 m-0 stat-head">Average Over/Under by Course Style</h6>
      </li>
      <% current_user.avg_by_style.each do |hash| %>
        <li class="list-group-item p-1">
          <small><%= "#{hash.keys.first} | #{hash.values.first}" %></small>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col">
    <ul class="list-group text-center mt-2">
      <li class="list-group-item list-group-item-secondary p-2">
        <h6 class="p-0 m-0 stat-head">Average Over/Under By Tee</h6>
      </li>
      <% current_user.avg_by_tee.each do |hash| %>
        <li class="list-group-item p-1">
          <small><%= "#{hash.keys.first} | #{hash.values.first}" %></small>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col">
    <ul class="list-group text-center mt-2">
      <li class="list-group-item list-group-item-secondary p-2">
        <h6 class="p-0 m-0 stat-head">Average Over/Under By Par</h6>
      </li>
      <% current_user.avg_by_par.each do |hash| %>
        <li class="list-group-item p-1">
          <small><%= "Par #{hash.keys.first} | #{hash.values.first}" %></small>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/main/_best_holes.html.erb
<div class="container p-0">
  <h5 class="mt-4">Best Holes</h5>
    <% if current_user.scorecards.blank? %>
      <h6 class="mb-5">No holes golfed yet...</h6>
    <% else %>
    <table class="table nord text-center mb-5">
      <thead class="thead nord-head">
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Hole/Course</th>
          <th scope="col">Tees</th>
          <th scope="col">Par</th>
          <th scope="col">Strokes</th>
          <th scope="col">Over/Under</th>
          <th scope="col">Round</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.best_holes.each do |hole| %>
          <tr>
            <td><%= hole.round.datef %></td>
            <td>#<%= hole.hole_number %> <%= hole.round.course.name %></td>
            <td><%= hole.round.tee %></td>
            <td><%= hole.par %></td>
            <td><%= hole.strokes %></td>
            <td><%= hole.over_under %></td>
            <td><%= link_to 'View', hole_path(hole), class: "btn-sm btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/main/_best_rounds.html.erb
<div class="container p-0">
  <h5 class="mt-4">Best Rounds</h5>
    <% if current_user.rounds.blank? %>
      <h6 class="mb-5">No rounds yet...</h6>
    <% else %>
    <table class="table nord text-center mb-5">
      <thead class="thead nord-head">
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Course</th>
          <th scope="col">Tees</th>
          <th scope="col">Par</th>
          <th scope="col">Strokes</th>
          <th scope="col">Over/Under</th>
          <th scope="col">Round</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.best_rounds.each do |round| %>
          <tr>
            <td><%= round.datef %></td>
            <td><%= round.course.name %></td>
            <td><%= round.tee %></td>
            <td><%= round.par %></td>
            <td><%= round.total %></td>
            <td><%= round.over_under %></td>
            <td><%= link_to 'View', round, class: "btn-sm btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/main/_index_holes.html.erb
<div class="container p-0">
  <h5 class="mt-4">Best Holes</h5>
    <% if current_user.scorecards.blank? %>
      <h6 class="mb-5">No holes golfed yet...</h6>
    <% else %>
    <table class="table nord text-center mb-5">
      <thead class="thead nord-head">
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Hole/Course</th>
          <th scope="col">Tees</th>
          <th scope="col">Par</th>
          <th scope="col">Strokes</th>
          <th scope="col">Over/Under</th>
          <th scope="col">Round</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.best_holes.each do |hole| %>
          <tr>
            <td><%= hole.round.datef %></td>
            <td>#<%= hole.hole_number %> <%= hole.round.course.name %></td>
            <td><%= hole.round.tee %></td>
            <td><%= hole.par %></td>
            <td><%= hole.strokes %></td>
            <td><%= hole.over_under %></td>
            <td><%= link_to 'View', hole.round, class: "btn-sm btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/main/_score_types.html.erb
<div class="row nord-row">
    <div class="col my-2 text-center">
      <h6>Hole-In-One</h6>
      <h4><%= current_user.scorecards.hole_in_one.count %></h4>
    </div>
    <div class="col my-2 text-center">
      <h6>Albatross</h6>
      <h4><%= current_user.scorecards.albatross.count %></h4>
    </div>
    <div class="col my-2 text-center">
      <h6>Eagle</h6>
      <h4><%= current_user.scorecards.eagle.count %></h4>
    </div>
    <div class="col my-2 text-center">
      <h6>Birdie</h6>
      <h4><%= current_user.scorecards.birdie.count %></h4>
    </div>
    <div class="col my-2 text-center">
      <h6>Par</h6>
      <h4><%= current_user.scorecards.parr.count %></h4>
    </div>
    <div class="col my-2 text-center">
      <h6>Bogey</h6>
      <h4><%= current_user.scorecards.bogey.count %></h4>
    </div>
    <div class="col my-2 text-center">
      <h6>Double-Bogey</h6>
      <h4><%= current_user.scorecards.double_bogey.count %></h4>
    </div>
</div>

app/views/main/index.html.erb
<h1 class="mt-5 mb-4 text-center">StatCaddie</h1>
<div class="row justify-content-center text-center">
  <div class="col-sm-6">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Create Courses</h5>
        <p class="card-text">Create your own courses or use coures others have already created</p>
        <%= link_to "See courses", courses_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Log Rounds</h5>
        <p class="card-text">Save detailed scorecards for rounds you've played</p>
        <%= link_to "See rounds", rounds_path, class: "btn btn-success" %>
      </div>
    </div>
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Track Stats</h5>
        <p class="card-text">Keep track of stats based on the rounds, tees, holes and courses you've played</p>
        <%= link_to "See stats", stats_path, class: "btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/main/stats.html.erb
<div class="container">
  <div class="row mb-0">
    <div class="col-3 px-0">
      <h1><%= current_user.name %></h1> 
      <h5>Signup: <%= current_user.created_at.strftime("%m/%d/%Y") %></h5> 
      <p class="badge badge-secondary">Rounds Golfed: <%= current_user.rounds.count %></p>
      <p class="badge badge-secondary">Created Courses: <%= current_user.created_courses.count %></p>
    </div>
    <div class="col my-4 text-center align-self-end nord-col">
      <h6>Average Strokes</h6>
      <h4><%= current_user.average_round %></h4>
    </div>
    <div class="col my-4 text-center align-self-end nord-col">
      <h6>Average Round</h6>
      <h4><%= current_user.average_score %></h4>
    </div>
    <div class="col my-4 text-center align-self-end nord-col">
      <h6>Average Putts</h6>
      <h4><%= current_user.average_putts %></h4>
    </div>
    <div class="col my-4 text-center align-self-end nord-col">
      <h6>Average Fairways</h6>
      <h4><%= current_user.average_fairways %></h4>
    </div>
    <div class="col-2 px-0 align-self-end">
      <%= link_to 'Create Course', new_course_path, class: "btn-sm btn-primary float-right" %><br><br>
      <%= link_to 'New Round', rounds_factory_path, class: "btn-sm btn-info float-right" %><br><br>
    </div>
  </div>
</div>

<%= render 'score_types' %> 

<%= render 'averages' %>

<%= render 'best_rounds' %>

<%= render 'best_holes' %>