config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'main#index'

  get '/rounds/factory', to: 'rounds#factory'
  get '/my_courses', to: 'courses#index_created'
  get '/golfed_courses', to: 'courses#index_golfed'
  get '/my_rounds', to: 'rounds#index_user'
  get '/course_rounds', to: 'rounds#index_course'
  get '/stats', to: 'main#stats'

  resources :rounds, shallow: true do
    resources :scorecards
  end

  resources :courses, shallow: true do
    resources :tees, except: [:show]
    resources :holes
  end

  resources :courses do
    resources :tees, only: [:show]
  end


end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :golfer, class_name: "User"
  belongs_to :course
  has_many :scorecards, dependent: :destroy
  has_many :tees, through: :course
  has_many :holes, through: :tees

  validates :date, :tee, presence: true

  accepts_nested_attributes_for :scorecards, allow_destroy: true, reject_if: :all_blank

  def total
    self.scorecards.sum(:strokes)
  end

  def par
    self.scorecards.sum(:par)
  end

  def style
    self.course.style
  end

  def total_putts
    self.scorecards.sum(:putts)
  end

  def total_gir
    self.scorecards.where(gir: true).count
  end

  def total_fairways
    self.scorecards.where(fairway: true).count
  end

  def over_under_num
    self.total - self.par
  end

  def over_under
    ou = self.total - self.par
    if ou > 0
      "+#{ou}"
    elsif ou == 0
      "E"
    else
      ou
    end
  end

  def datef
    self.date.strftime("%-m/%-d/%Y")
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_round, only: [:show, :edit, :update, :destroy]
  before_action :modify_round_permission, except: [:index, :factory, :index_user, :index_course, :new, :create, :show]

  def index
    @rounds = Round.order(date: :desc).paginate(page: params[:page], per_page: 15)
  end

  def index_user
    @rounds = current_user.rounds.order(date: :desc).paginate(page: params[:page], per_page: 15)
    render 'index'
  end

  def index_course
    @rounds = Round.where(Round.arel_table[:course_id]
      .in(current_user.created_courses.pluck(:id))).order(date: :desc)
      .paginate(page: params[:page], per_page: 15)
    render 'index'
  end

  def create
    @round = Round.create(round_params)
    if @round.valid?
      18.times do |i|
        @round.scorecards.build(hole_number: i+1)
      end
      render 'scorecards'
    else
      flash.now[:alert] = @round.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def show
  end

  def edit
    add_holes
  end

  def update
    @round.update(round_params)
    if @round.valid?
      redirect_to round_path(@round), alert: "Round updated successfully"
    else
      error_check('edit')
    end
  end

  def destroy
    @round.destroy
    redirect_to my_rounds_path, notice: "Successfully deleted."
  end

  def factory
    if params[:state].nil?
      render 'form_state'
    elsif params[:state] && params[:city].nil?
      @courses = Course.where(state: params[:state])
      render 'form_city'
    elsif params[:state] && params[:city] && params[:name].nil?
      @courses = Course.where(state: params[:state], city: params[:city])
      render 'form_course'
    elsif params[:state] && params[:city] && params[:name]
      course = Course.find_by(state: params[:state], city: params[:city], name: params[:name])
      @round = current_user.rounds.new(course: course)
      render 'new'
    else
      flash.now[:alert] = "There was an error. Please try again"
      render 'form_state'
    end
  end

  private

  def set_round
    unless @round = Round.find_by(id: params[:id])
      redirect_to rounds_path, alert: "Could not find a round with that ID."
    end
  end

  def error_check(view)
    flash.now[:alert] = @round.errors.full_messages.join(', ')
    render view
  end

  def round_params
    params.require(:round).permit(:course_id, :golfer_id, :date, :tee,
                                  scorecards_attributes: [:fairway, :gir, :hole_number, :notes, :putts, :strokes, :id])
  end

  def add_holes
    (18 - @round.scorecards.count).times do
      @round.scorecards.build
    end
  end

  def modify_round_permission
    redirect_to my_rounds_path, alert: "Sorry. You can only modify rounds you've created." if @round.golfer_id != current_user.id
  end

end

app/helpers/rounds_helper.rb
module RoundsHelper

  def mod_perm(user)
    if user_signed_in?
      true if current_user == user
    end
  end

  def boolean_circle(bool)
    if bool
      '<p class="text-success">&#9679;</p>'
    else
      '<p class="text-danger">&#9679;</p>'
    end
  end

end

app/views/rounds/_form_state.html.erb
<%= form_with url: { action: :factory }, method: 'get', local: true do %>
  <div class="form-group">
    <%= label_tag :state %>
    <%# <%= select_tag :state, options_for_select(Course.pluck(:state).uniq.sort), { prompt: "Select one" }, { class: "form-control" } %1> %>
    <%= select_tag :state, options_for_select(Course.pluck(:state).uniq.sort), class: "form-control" %>
  </div>
  <div class="actions">
    <%= submit_tag "Next", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rounds/_show_scorecard.html.erb
      <ul class="list-group list-group-flush text-center mt-2" style="width: 11%">
        <li class="list-group-item list-group-item-secondary p-2">
          <small class="form-text"><%= link_to "Hole #{scorecard.hole_number}", Hole.find_by(lid: scorecard.lid), class: "nord-link" %></small>
          <small class="form-text">Par <%= scorecard.par %></small>
          <small class="form-text"><%= scorecard.yardage %> yds</small>
        </li>
        <li class="list-group-item p-1">
          <small class="form-text text-muted">Strokes</small>
          <% if scorecard.strokes < scorecard.par  %>
            <small class="form-text text-success"><%= scorecard.strokes %></small>
          <% elsif scorecard.strokes == scorecard.par %>
            <small class="form-text"><%= scorecard.strokes %></small>
          <% else %>
            <small class="form-text text-danger"><%= scorecard.strokes %></small>
          <% end %>
        </li>
        <li class="list-group-item p-1">
          <small class="form-text text-muted">Putts</small>
          <small class="form-text"><%= scorecard.putts %></small>
        </li>
        <li class="list-group-item p-1">
          <small class="form-text text-muted">G.I.R.</small>
          <% if scorecard.gir %>
            <p class="text-success">&#9679;</p>
          <% else %>
            <p class="text-danger">&#9679;</p>
          <% end %>
        </li>
        <li class="list-group-item p-1">
          <small class="form-text text-muted">Fairway</small>
          <% if scorecard.fairway %>
            <p class="text-success">&#9679;</p>
          <% else %>
            <p class="text-danger">&#9679;</p>
          <% end %>
        </li>
      </ul>

app/views/rounds/edit.html.erb
<div class="container">
  <div class="row mb-0">
    <div class="col-8 px-0">
      <h1>Edit Round</h1>
      <h3><%= @round.course.name %> | <%= @round.datef %></h3> 
      <h5><%= "#{@round.course.city}, #{@round.course.state}" %></h5> 
      <p class="badge badge-secondary"><%= @round.course.access %></p>
      <p class="badge badge-secondary"><%= @round.course.style %></p>
    </div>
  </div>
</div>
<%= form_with model: @round, local: true do |f| %>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tee %>
    <%= f.select :tee, options_for_select(@round.course.tees.pluck(:color).sort, selected: f.object.tee), { prompt: "Select Tee.." }, { class: "form-control" } %>
  </div>
  <div class="container mb-4">
    <div class="row">
      <%= f.fields_for :scorecards do |ff| %>
        <%= render 'scorecards/form_fields', f: ff %>
      <% end %>
    </div>
  </div>
  <div class="actions">
    <%= submit_tag "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rounds/form_city.html.erb
<h1>New Round</h1>
<%= form_with url: { action: :factory }, method: 'get', local: true do %>
  <div class="row">
    <div class="col-auto pr-1">
      <h5>State:</h5>
    </div>
    <div class="col-auto">
      <h6><%= @courses.first.state %></h6> 
    </div>
  </div>
  <div class="form-group">
    <%= hidden_field_tag :state, @courses.first.state %>
    <%= label_tag :city %>
    <%= select_tag :city, options_for_select(@courses.pluck(:city).uniq.sort), class: "form-control" %>
  </div>
  <div class="actions">
    <%= submit_tag "Next", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rounds/form_course.html.erb
<h1>New Round</h1>
<%= form_with url: { action: :factory }, method: 'get', local: true do %>
  <div class="row">
    <div class="col-auto pr-1">
      <h5>State:</h5>
    </div>
    <div class="col-auto">
      <h6><%= @courses.first.state %></h6> 
    </div>
  </div>
  <div class="row">
    <div class="col-auto pr-1">
      <h5>City:</h5>
    </div>
    <div class="col-auto">
      <h6><%= @courses.first.city %></h6> 
    </div>
  </div>
  <div class="form-group">
    <%= hidden_field_tag :state, @courses.first.state %>
    <%= hidden_field_tag :city, @courses.first.city %>
    <%= label_tag :name, "Course" %>
    <%= select_tag :name, options_for_select(@courses.pluck(:name).uniq.sort), class: "form-control" %>
    <%# <%= label_tag :holes, "Holes Played" %1> %>
    <%# <%= select_tag :holes, options_for_select([9, 18]), class: "form-control" %1> %>
  </div>
  <div class="actions">
    <%= submit_tag "Next", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rounds/form_state.html.erb
<h1>New Round</h1>
<%= form_with url: { action: :factory }, method: 'get', local: true do %>
  <div class="form-group">
    <%= label_tag :state %>
    <%# <%= select_tag :state, options_for_select(Course.pluck(:state).uniq.sort), { prompt: "Select one" }, { class: "form-control" } %1> %>
    <%= select_tag :state, options_for_select(Course.pluck(:state).uniq.sort), class: "form-control" %>
  </div>
  <div class="actions">
    <%= submit_tag "Next", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rounds/index.html.erb
<div class="row">
  <div class="col">
    <h1>Rounds</h1>
  </div>
  <div class="col align-self-center">
    <%= link_to 'Add Round', rounds_factory_path, class: "btn-sm btn-primary float-right" %>
  </div>
</div>
<br><br>
<table class="table nord text-center">
  <thead class="thead nord-head">
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Course</th>
      <th scope="col">Holes</th>
      <th scope="col">Par</th>
      <th scope="col">Strokes</th>
      <th scope="col">Over/Under</th>
      <th scope="col">Putts</th>
      <th scope="col">G.I.R.</th>
      <th scope="col">Fairways</th>
      <th scope="col">Golfer</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>

    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.datef %></td>
        <td><%= link_to round.course.name, round.course %></td>
        <td><%= round.scorecards.count %></td>
        <td><%= round.par %></td>
        <td><%= round.total %></td>
        <td><%= round.over_under %></td>
        <td><%= round.scorecards.sum(:putts) %></td>
        <td><%= round.total_gir %></td>
        <td><%= round.total_fairways %></td>
        <td><%= round.golfer.name %></td>
        <td><%= link_to 'View', round, class: "btn-sm btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @rounds, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<% if @rounds.blank? %>
  <h6>No rounds yet...</h6>
<% end %>

app/views/rounds/new.html.erb
<h1>New Round</h1>
<%= form_with model: @round, local: true do |f| %>
  <%= f.hidden_field :course_id, value: @round.course.id %>
  <%= f.hidden_field :golfer_id, value: @round.golfer.id %>
  <%= f.hidden_field :holes, value: params[:holes] %>
  <div class="row">
    <div class="col-auto pr-1">
      <h5>State:</h5>
    </div>
    <div class="col-auto">
      <h6><%= @round.course.state %></h6> 
    </div>
  </div>
  <div class="row">
    <div class="col-auto pr-1">
      <h5>City:</h5>
    </div>
    <div class="col-auto">
      <h6><%= @round.course.city %></h6> 
    </div>
  </div>
  <div class="row">
    <div class="col-auto pr-1">
      <h5>Course:</h5>
    </div>
    <div class="col-auto">
      <h6><%= @round.course.name %></h6> 
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tee %>
    <%= f.select :tee, options_for_select(@round.course.tees.pluck(:color).sort), { prompt: "Select Tee.." }, { class: "form-control" } %>
  </div>
  <div class="actions">
    <%= submit_tag "Next", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rounds/scorecards.html.erb
<div class="container">
  <div class="row mb-0">
    <div class="col-8 px-0">
      <h1>New Round</h1></h1> 
      <h3><%= @round.course.name %> | <%= @round.datef %></h5> 
      <h5><%= "#{@round.course.city}, #{@round.course.state}" %></h5> 
      <p class="badge badge-secondary"><%= @round.course.access %></p>
      <p class="badge badge-secondary"><%= @round.course.style %></p>
    </div>
  </div>
</div>

<%= form_with model: @round, local: true do |f| %>
  <%= f.hidden_field :id, value: @round.id %>
  <div class="container mb-4">
    <div class="row">
      <%= f.fields_for :scorecards do |ff| %>
        <%= render 'scorecards/form_fields', f: ff %>
      <% end %>
    </div>
  </div>

  <%= f.submit "Create Scorecard", class: "btn btn-primary" %>

<% end %>

app/views/rounds/show.html.erb
<div class="container">
  <div class="row mb-0">
    <div class="col-8 px-0">
      <h1>Round at <%= link_to @round.course.name, @round.course %></h1> 
      <h5><%= @round.datef %> | <%= "#{@round.course.city}, #{@round.course.state}" %></h5> 
      <h5>Golfer: <%= @round.golfer.name %></h5> 
      <h6><%= @round.tee %> Tees | Par <%= @round.par %></h6> 
      <p class="badge badge-secondary"><%= @round.course.access %></p>
      <p class="badge badge-secondary"><%= @round.course.style %></p>
    </div>
    <div class="col px-0 align-self-end">
      <h3 class="float-right">Strokes: <%= @round.total %> | <%= @round.over_under %></h3><br><br>
      <% if mod_perm(@round.golfer) %>
        <%= link_to 'Edit Round', edit_round_path(@round), class: "btn-sm btn-secondary float-right" %><br><br>
        <%= link_to 'Delete Round', @round, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger float-right" %><br><br>
      <% end %>
    </div>
  </div>
</div>

<div class="container mb-4">
  <div class="row">

    <% @round.scorecards.each do |scorecard| %>
      <%= render 'show_scorecard', scorecard: scorecard %>
    <% end %>

  </div>
</div>