config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'main#index'

  get '/rounds/factory', to: 'rounds#factory'
  get '/my_courses', to: 'courses#index_created'
  get '/golfed_courses', to: 'courses#index_golfed'
  get '/my_rounds', to: 'rounds#index_user'
  get '/course_rounds', to: 'rounds#index_course'
  get '/stats', to: 'main#stats'

  resources :rounds, shallow: true do
    resources :scorecards
  end

  resources :courses, shallow: true do
    resources :tees, except: [:show]
    resources :holes
  end

  resources :courses do
    resources :tees, only: [:show]
  end


end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-4">
  <span class="golf-icon"><i class="fas fa-golf-ball fa-2x"></i></span>
  <a class="navbar-brand golf pl-2" href="#">StatCaddie</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav nord-nav mr-auto">
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Courses
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Courses", courses_path, class: "dropdown-item" %>
          <%= link_to "Golfed Courses", golfed_courses_path, class: "dropdown-item" %>
          <%= link_to "Created Courses", my_courses_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rounds
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Rounds", rounds_path, class: "dropdown-item" %>
          <%= link_to "My Rounds", my_rounds_path, class: "dropdown-item" %>
          <%= link_to "Rounds at Created Courses", course_rounds_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item"><%= link_to "Stats", stats_path, class: "nav-link" %></li>
    </ul>

    <ul class="nav navbar-nav nord-nav navbar-right">
      <% if user_signed_in? %>
        <%= fa_icon "user", class: 'user-icon', size: '1x' %>
        <li class="nav-item"><%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link nord-logout" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
      <% end %>
    </ul>

  </div>
</nav>