config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'main#index'

  get '/rounds/factory', to: 'rounds#factory'
  get '/my_courses', to: 'courses#index_created'
  get '/golfed_courses', to: 'courses#index_golfed'
  get '/my_rounds', to: 'rounds#index_user'
  get '/course_rounds', to: 'rounds#index_course'
  get '/stats', to: 'main#stats'

  resources :rounds, shallow: true do
    resources :scorecards
  end

  resources :courses, shallow: true do
    resources :tees, except: [:show]
    resources :holes
  end

  resources :courses do
    resources :tees, only: [:show]
  end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update, :index_golfed, :index_created]
  before_action :set_course, only: [:show, :edit, :destroy, :update]
  before_action :modify_course_permission, only: [:edit, :destroy, :update]

  def index
    @courses = Course.by_state.paginate(page: params[:page], per_page: 15)
  end

  def index_golfed
    @courses = current_user.courses.paginate(page: params[:page], per_page: 15)
    render 'index'
  end

  def index_created
    @courses = current_user.created_courses.paginate(page: params[:page], per_page: 15)
    render 'index'
  end

  def new
    @course = Course.new
  end

  def create
    @course = current_user.created_courses.create(course_params)
    error_check('new')
  end

  def show
  end

  def edit
  end

  def update
    @course.update(course_params)
    error_check('edit')
  end

  def destroy
    @course.destroy
    redirect_to courses_path, notice: "Course succesfully deleted."
  end

  private

  def set_course
    @course = Course.find_by(id: params[:id])
    redirect_to courses_path, alert: "Sorry. That course does not exist." if @course.nil?
  end

  def modify_course_permission
    redirect_to courses_path, alert: "Sorry. You can only modify courses you've created." if @course.creator_id != current_user.id
  end

  def error_check(view)
    if @course.valid?
      redirect_to course_path(@course)
    else
      flash.now[:alert] = @course.errors.full_messages.join(', ')
      render view 
    end
  end

  def course_params
    params.require(:course).permit(:name, :city, :state, :access, :style)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper

  def mod_perm(user)
    if user_signed_in?
      true if current_user == user
    end
  end

end

app/views/courses/_course_summary.html.erb
<div class="container">
  <div class="row mb-0">
    <div class="col-8 px-0">
      <h1><%= course.name %></h1> 
      <h5><%= "#{course.city}, #{course.state}" %></h5> 
      <p class="badge badge-secondary"><%= course.access %></p>
      <p class="badge badge-secondary"><%= course.style %></p>
    </div>
    <div class="col px-0 align-self-end">
      <% if mod_perm(course.creator) %>
        <%= link_to 'Edit Course Info', edit_course_path(course), class: "btn-sm btn-secondary float-right" %><br><br>
        <%= link_to 'Delete Course', course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger float-right" %><br><br>
        <%= link_to 'Add Tees', new_course_tee_path(course), class: "btn-sm btn-success float-right" %><br><br>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/_form.html.erb
<%= form_with model: course, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :style %><br>
    <%= f.select :style, options_for_select(Course.pluck(:style).uniq.sort), { prompt: "Select one" }, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :access %>
    <%= f.select :access, options_for_select(Course.pluck(:access).uniq.sort), { prompt: "Select one" }, { class: "form-control" } %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/_tee_holes.html.erb
<div class="container mb-4">
  <div class="row">
    <div class="col-auto px-0">
      <h6><%= tee.color %> Tees</h6>
    </div>
    <div class="col-auto pl-3">
      <%= link_to "View", course_tee_path(tee.course, tee), class: "badge badge-primary" %>
      <% if mod_perm(tee.course.creator) %>
        <%= link_to "Edit", edit_tee_path(tee), class: "badge badge-secondary" %>
        <%= link_to 'Delete', tee, method: :delete, data: { confirm: 'Are you sure?' }, class: "badge badge-danger" %>
      <% end %>
    </div>
    <div class="col-auto ml-auto mt-1 pr-2">
      <h6>Par: <%= tee.par %> | <%= tee.yardage %> yards</h6>  
    </div>
  </div>
  <div class="row">
    <% tee.holes.each do |hole| %>
      <ul class="list-group list-group-flush text-center mt-2" style="width: 11%">
        <li class="<%= "list-group-item #{tee_list_group_style(tee)} p-2"%>"><small><%= hole.hole_number %></small></li>
        <li class="list-group-item p-1"><small><%= hole.yardage %></small></li>
        <li class="list-group-item p-1"><small><%= hole.par %></small></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>
<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col">
    <h1>Courses</h1>
  </div>
  <div class="col align-self-center">
    <%= link_to 'Create Course', new_course_path, class: "btn-sm btn-primary float-right" %>
  </div>
</div>
<br><br>
<table class="table nord">
  <thead class="thead nord-head">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Style</th>
      <th scope="col">Access</th>
      <th scope="col">Created By</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.city %></td>
        <td><%= course.state %></td>
        <td><%= course.style %></td>
        <td><%= course.access %></td>
        <td><%= course.creator.name %></td>
        <td><%= link_to 'View', course, class: "btn-sm btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @courses, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/courses/new.html.erb
<h1>New Course</h1>
<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<%= render 'course_summary', course: @course %>
<h5 class="mt-4">Best Rounds</h5>
  <% if @course.rounds.blank? %>
    <h6 class="mb-5">No rounds yet...</h6>
  <% else %>
  <table class="table nord text-center mb-5">
    <thead class="thead nord-head">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Tees</th>
        <th scope="col">Golfer</th>
        <th scope="col">Par</th>
        <th scope="col">Strokes</th>
        <th scope="col">Over/Under</th>
        <th scope="col">Round</th>
      </tr>
    </thead>

    <tbody>
      <% @course.best_rounds.each do |round| %>
        <tr>
          <td><%= round.datef %></td>
          <td><%= round.tee %></td>
          <td><%= round.golfer.name %></td>
          <td><%= round.par %></td>
          <td><%= round.total %></td>
          <td><%= round.over_under %></td>
          <td><%= link_to 'View', round, class: "btn-sm btn-secondary" %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>


<div class="row">
  <% @course.tees.each do |tee| %>
    <div class="col-6">
      <%= render 'tee_holes', tee: tee %>
    </div>
  <% end %>
</div>